using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.XAML;
using Content.Client.DeltaV.Arcade.S3D.Renderer;
using Content.Shared.DeltaV.Arcade.S3D;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.DeltaV.Arcade.S3D.UI;

[GenerateTypedNameReferences]
public sealed partial class S3DMenu : FancyWindow
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    public S3DMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        // Is it possible to add arbitrary (i.e. non-default) controls like this in XAML? This stuff is so undocumented...
        var renderer = new S3DRenderer(new S3DState(22, 12, -1, 0, 0, 0.66));
        renderer.SetSize = new Vector2(800, 600);
        renderer.CanKeyboardFocus = true;
        MainScreen.AddChild(renderer);
    }
}
